### ISSUE TITLE
Upgrade all projects to use .NET 4.5.

### ISSUE THREAD

**Issue by PureKrome** [SimpleAuthentication/SimpleAuthentication#142]

**Comment by Dashue** [comment]
Does this mean it won't work to use it from a project targeting 4.5 until this task is done?

**Comment by PureKrome** [comment]
nope. the _current_ nuget packages are targetting 4.0 .. which is 100% compat with 4.5 (as far as i know).

the reason why i wanted to update the library to 4.5 was to take advantage of `async/await`. - which is all in a [separate branch](https://github.com/PureKrome/SimpleAuthentication/tree/milestone/2.0).

**Comment by hlesesne** [comment]
I'm getting the following error when tagetting 4.5:

Could not load type 'SimpleAuthentication.Core.ICache' 

I opened a separate issue #175 , but then searched and found this thread.

**Comment by phillip-haydon** [comment]
V2 will be .NET 4.5 only.
