### ISSUE TITLE
Considering changing the default routes.

### ISSUE THREAD

**Issue by PureKrome** [SimpleAuthentication/SimpleAuthentication#143]
Phillip, I'm considering changing the default routes for 2.0 to be

Redirecting to a provider (eg. google):
Current: `/authentication/redirect/{providerkey}`
New: `/authenticate/{provider}` eg. `/authenticate/google`

Returning back to your website (ie, the callback)
Current: `/authentication/authenticatecallback`
New: `authenticate/callback`

of course, this means there cannot be an authentication provider called `callback` :stuck_out_tongue:

**Comment by phillip-haydon** [comment]
V2 we will have configurable routes for OWIN fall through.
