### ISSUE TITLE
Provide a way to configure additional scopes for providers

### ISSUE THREAD

**Issue by Dashue** [SimpleAuthentication/SimpleAuthentication#162]
It would be real handy if there was a way to leverage simpleauthentication for retrieving accestoken with elevated permissions.

My use case stems from me wanting to pull extra info from linkedin.

The scenario currently looks like:
LinkedInProvider uses the minimal permisssions that simpleauth needs to retrieve the basic info (r_basicprofile and r_emailaddress). (These are currently hardcoded in the defaultscopes of the provider impl)
What I need need to do is use something else, or roll my own functionality for elavating those permissions to (r_fullprofile).

It would provide a better experience if it was possible to add additional scopes, leveraging simpleauth to give me an elevated accesstoken straight away.

I believe there's been talk of configurable/extensible scope before, I'd like to chip in with my time to make this a reality.

I hope this is enough to paint the picture, if not let me know and I'll try to fill in the missing pieces.
Cheerio

**Comment by PureKrome** [comment]
Hi again @Dashue,

ok - :heart: it when people offer to help :+1: :clap: 

First of all, you should work off the [2.0-.net4.5)[https://github.com/SimpleAuthentication/SimpleAuthentication/tree/2.0-.net4.5] branch.

Second, lets talk about this idea of yours - mainly so i _understand_ the question.

Lets look at some sample code

```c#
protected override IEnumerable<string> DefaultScopes
{
    get { return new[] { "r_basicprofile", "r_emailaddress" }; }
}
```

Ok, so this is hardcoded and should be replaced with an _option_ in the `web.config`.

Lets look at a sample `web.config` file:
`<add key="sa.Google" value="key:587140099194.apps.googleusercontent.com;secret:npk1_gx-gqJmLiJRPFooxCEY" />`

So the value needs to be delimited by something (eg. a `;`) which will then take another delimited list of strings, which are the scopes.

eg.
`<add key="sa.Google" value="key:587140099194.apps.googleusercontent.com;secret:npk1_gx-gqJmLiJRPFooxCEY;r_basicprofile,r_emailaddress,r_pewpew" />`

Now, if that is what you're talking about, then we can 
1. Each provider needs to provide a _default_ scope list if none exists in the config file
2. Parse the key and strip out the `scopes` value (which is a csv string)
3. set the provider scopes value from the config file, if provided.

**Comment by Dashue** [comment]
Yup, that's what I was referring to, 

In regards to 1: The reason i'm thinking of more in regards of extending the scopes, is because it good to support the minimal, out of the box. 
For example the linkedi provider, needs r_basicprofile and r_emailaddress for the basic data. As a sure I'd like to add r_fullprofile, with overriding this would lose r_emailaddress, with extension it would leave me with r_basicprofile, r_mailaddress, r_fullprofile.

I had not gotten as far as consider it web.config based, I am configuring it in code now and was thinking it could be provided through a static typed approach, however I believe the web.config proposed solution is superior when thinking about it.

**Comment by PureKrome** [comment]
I was also thinking about this: whatever the developer sticks into the `web.config` `<add key../>` line .. it would be -all- the scopes required. Not just the _extra_ scopes. Basically, if you're going to add the scopes, u know what you're doing... so add _all_ the scopes you need.

**Comment by Dashue** [comment]
Yeah you're probably right, otherwise you kind of have to know that the linkedinprovider uses r_basicprofile and r_emailaddress underneath the hood, unless it would distinct the values and any duplicates wouldn't have an impact.

Should there be a :scopes in the config string
`<add key="sa.Google" value="key:587140099194.apps.googleusercontent.com;secret:npk1_gx-gqJmLiJRPFooxCEY;scopes:r_basicprofile,r_emailaddress,r_pewpew" />`

With the assumption being that it should be happy-path, what would this do
`<add key="sa.Google" value="key:587140099194.apps.googleusercontent.com;secret:npk1_gx-gqJmLiJRPFooxCEY;scopes:" />`

**Comment by PureKrome** [comment]
>Should there be a `scopes:` in the config string?
yes. Refer to my example, above.

>With the assumption being that it should be H-P like this.
Nope.

This is the 99% super-dupa-happy-path example:
`<add key="sa.Google" value="key:587140099194.apps.googleusercontent.com;secret:npk1_gx-gqJmLiJRPFooxCEY" />`

(notice how there's _no_ scopes segment defined?

and the 1%'ers...

`<add key="sa.Google" value="key:587140099194.apps.googleusercontent.com;secret:npk1_gx-gqJmLiJRPFooxCEY;scopes:a,b,c,d,e..." />`

**Comment by PureKrome** [comment]
Heya - this reply might be a bit late but I was looking at the code in my branch today and noticed that already exists .. at least in my 2.0-.net-4.5 branch.

**Comment by Dashue** [comment]
Better late than never :)
