### ISSUE TITLE
SystemHelpers.CreateCallBackUri using port of requestUrl doesn't work in common deployments

### ISSUE THREAD

**Issue by fschwiet** [SimpleAuthentication/SimpleAuthentication#167]
When I deploy a site using SimpleAuthentication behind a firewall, authentication fails at https://accounts.google.com/o/oauth2/auth.  The error message says "The redirect URI in the request: http://www.192.168.33.100.xip.io:5000/authentication/authenticatecallback?providerkey=google".

The problem is that the redirect url in the request should be using port 80, not 5000.  Nginx is configured to listen to www.192.168.33.100.xip.io:80 and redirect to <otherIP>:5000 where the site is running internally.  For other auth packages I've had (http://passportjs.org/docs) this is not a problem as the internal OAuth url is configurable.  There may be a standard request header you can rely on instead that would be site by the firewall/proxy), I am looking into that.

https://github.com/SimpleAuthentication/SimpleAuthentication/blob/bf4f9b782603b1cd3f7dcec3ae7ebc1e9ba515c8/Code/SimpleAuthentication.Core/SystemHelpers.cs#L53

**Comment by fschwiet** [comment]
Update:  It looks appropriate to use the Host request header for the <host>:<port> portion of the url, if present.

**Comment by fschwiet** [comment]
Following where the request url originates in SimpleAuthentication into Nancy's source, it looks to be based on HttpListenerRequest.Url which is documented to use the host header appropriately.  So I am uncertain if this is really a SimpleAuthentication issue or another component.

**Comment by PureKrome** [comment]
Heya @fschwiet - I've been putting our :fire:'s at work for the last week but I will try and endeavour to have a looksies at this in a few days time :disappointed: 

So i'm not trying to be quiet or avoid this thread. Just ... really hella busy :blush:

**Comment by fschwiet** [comment]
I found that when I host with OWIN/Katana I do not have the problem, only when I use nancy self-hosting.  So to me it does not seem like the bug is in SimpleAuthentication.

**Comment by PureKrome** [comment]
:+1:  ta!
