### ISSUE TITLE
Support for facebook api v2.4

### ISSUE THREAD

**Issue by wk001** [SimpleAuthentication/SimpleAuthentication#173]
Hi,

The current FacebookProvider doesn't completely work the  v2.4 of FB's api.  While it does authenticate successfully it doesn't retrieve any of the user's details as, I believe, there were breaking changes to api.  A caller must now provide a comma separated list of _fields_ in the call to the 'me' api.

eg
```
var restRequest = new RestRequest("me");
restRequest.AddParameter("access_token", accessToken.PublicToken);
restRequest.AddParameter("fields", "name,email");
```

(As a result of this the code that parses the response.Data for the user's name need only use response.Data.Name rather than joining first and last name)

I'm quite happy to submit a PR but I don't want to break pre v2.4 clients.  Do you intend to support multiple versions of each provider's api?  Or perhaps you see this as a responsibility of the client - hence you pass the token to IAuthenticationCallbackProvider.Process - where a subsequent call could be made to return the client's details?

**Comment by PureKrome** [comment]
Hi @wk001 - thanks heaps for the issue. So the current version that is on NuGet is now, well, failing? This is because FB the current version of SA is using the FB api which now has a breaking change?

If this is the case (and mind you, I've just read this issue and therefore just learnt about FB's changed their api, etc and not re-looked at their api, release notes, docs, etc) ... then 

- can we specify the previous api version?
- why would we want to specify the new version?
- consumers of SA wouldn't really care about FB versions at all IMO - they just want the data.

NOTE: the idea of letting the developer determine the claims is a separate issue and _if_ (when?) the developer can set their claims, then I guess this would be a very valid thing to document to them - especially if the way claims are set, are different between API's. Possibly.

**Comment by wk001** [comment]
In answer to your questions regarding api version, it seems that new apps are, understandably, pinned to the new version of the api v2.4. "..Any call to a version earlier than this or unversioned call by this app will automatically get upgraded to this...".  This suggests that SA needs to support different versions of the FB api.

To be fair, SA is not **broken** if clients are only using it for authentication.  If, however, they're using SA to also retrieve claims (name, email etc) then the current implementation doesn't work out of the box.  As a workaround, I'm making a subsequent call to the "me" api with the list of **fields** I'd like returned.  This is easy to implement as the access token is passed to the callback implementation. But it means I've had to duplicate the code to call the "me" api - and the initial request is redundant. 

Have you suffered from similar issues from the other providers?  Does SA need an extension point to allow a user/claims-strategy? At the very least, it would be nice to have a re-useable abstraction.

**Comment by PureKrome** [comment]
> it seems that new apps are, understandably, pinned to the new version of the api v2.4. "..Any call to a version earlier than this or unversioned call by this app will automatically get upgraded to this...".

I'm guessing that SA is *unversioned* which means we're auto-using 2.4. 

>This suggests that SA needs to support different versions of the FB api.

Maybe. I'd prefer that the developer doesn't really care about these implementation details and just requests what scope(s) they want -- preferably in a format that is _not_ tied to an api version which means the developers need to read the SA docs -and- then FB's (or other provider) docs. I was trying to abstract away the pain of developers learning so much of the low level crap from every provider they wish to use.

>To be fair, SA is not broken if clients are only using it for authentication. If, however, they're using SA to also retrieve claims (name, email etc) then the current implementation doesn't work out of the box.

I disagree here. My attempt of SA was to do both -> you auth (ok, fine...) but magically behind the scenes I also grab the data. Wether the developer uses that or not, it's not my problem. But the goal was to 

- auth
- provide the user data as an option for the developer.

as such, point 2 is failing.

>Have you suffered from similar issues from the other providers?
This is the first issue raised re: this problem.

> Does SA need an extension point to allow a user/claims-strategy?
Hell yes. #85 

I think it's time do an emergency patch release that includes #85 and this issue.

**Comment by PureKrome** [comment]
Hi @wk001 - I'm trying to replicate this issue. I just cloned the current repo and switched to `master`. then ran the sample nancy app. logged in via FB and had a look at the output. All the fields are there except `username`.

Can you please give me some more info so I can try and replicate this .... so i can fix it, please?

**Comment by janoserdelyi** [comment]
You may need to make a new facebook application - the one you're testing
against might be grandfathered as far as API version/response. I ran into
this exact same issue - the sample would work, but using my own FB
application on new project work would fail in this exact same way that
wk001 described. i was crunched for time and this was one of the smaller
items, so i had to switch over to Facebook's javascript implementation, but
i would love to use this method instead.

**Comment by PureKrome** [comment]
@Janoserdelyi - mate, thanks for replying so promptly! :+1: 

AH! so it's also about creating an FB app which is where I get the app id / secret thingy from.

Gotcha. Will report back now.

**Comment by wk001** [comment]
As @janoserdelyi hinted, the problem exists for any app that's created against FB's 2.4 api.  I expect apps created before 2.4 will continue to work with SA.  

This poses a problem if you want to retain the goals stated above - ie keep SA api-version agnostic.  You could use some best-endeavors/chain-of-responsibility approach to retrieve user details - but this will undoubtedly incur additional network hops.  

As a developer I'd rather opt out of the default behavior (< 2.4), be explicit about the api version and reduce latency.   I still think a pluggable strategy would be good here.  SignIn and user-claims should be kept separate - the token passed from one to the other. 

Happy to contribute if you'd accept the pr..

**Comment by PureKrome** [comment]
@wk001 i've failed to figure out what's going on :/ So yeah, PR would be :heart: 

this is the sample URL i'm passing:

```
https://www.facebook.com/dialog/oauth?
client_id=<my new app i just created>
&redirect_uri=http://localhost:7000/authentication/authenticatecallback?providerkey=facebook
&scope=public_profile,email
&state=1b17e678-179c-48d1-8603-4ab0f5d3fc9e
```

(note: that state is random, each time).

That doesn't error .. and when i call `/me?..` i only get back TWO fields:

- `id`
- `name`

But I'm sure I've setup the scopes, properly.

Also, the change i've done to my current branch (to try and fix this) is to only add the default scope in: `public_profile`. I don't even need to add that in .. which means .... my previous _should_ work.

I'm really confused :/

**Comment by PureKrome** [comment]
Ignore my last comment. got it.

`https://graph....../me?fields=name,first_name,last_name,email`.. etc

Now for the next major PITA. FB has dropped the `UserName` so now I need to scrape this :/

**Comment by wk001** [comment]
OK, cool, but let me know if I can help.

Do you have a FB 2.3 (and lower) app you can test against?  I don't so hard to know if any changes break backwards compatibility.

**Comment by PureKrome** [comment]
>Do you have a FB 2.3 (and lower)

I sure do. the sample app that comes with the repo is v 2.0.

Also - [it looks like the `UserName` has to remain hidden now](http://stackoverflow.com/questions/32579581/facebook-login-api-has-a-missing-username) as under the ToS, etc. So this means, no username :/

As such, I'll start to prepare a new NuGet package and put it up for testing.

**Comment by wk001** [comment]
This only goes to show that a SA user should  be API version aware which suggests the need for a Strategy. This would avoid messy if statements/comments and introduce an extension point. 

Related to this might it be better to model the user as a dynamic?

**Comment by PureKrome** [comment]
Hmmm. I -really- don't want to have to have the developer *know* about which version of Facebook API they should use. That could really start to make things messy :(

I can put up a new NuGet that 
- uses the 2.4 api but that means *existing* users now need to set the `UserName` field.

or
- Add the ability for a developer to set their api version which determines if the `UserName` is `null` or not. What happens if they say: use v2.0 but their app was created at v2.3, etc? What about the `default` version if none is set by the developer?

and both options are breaking changes, so that a major jump in the semver, also (which I don't think we can avoid, now).

Lastly, I can't see how making the model `dynamic` solves anything - at least in this current state-of-the-repo. Part of the idea is to have a pretty simple standard `UserInformation` object that gets by as a pretty good average login-data. Anything else, then make another call to the service IMO.

@phillip-haydon - any thoughts on this?

**Comment by janoserdelyi** [comment]
i agree with the principle of not requiring a developer to specify the
version. being able to set it is nice, though - not sure if this is a
have-your-cake-and-eat-it-too dream or not programmatically for this.
at the very least being able to emit a read-only property back to the
client of what version is being hit? i'm just thinking about things which
may help illuminate future problems more quickly.

**Comment by PureKrome** [comment]
>at the very least being able to emit a read-only property back to the
client of what version is being hit?

That's do-able ... but I'm not sure ... where to do that? Like, it's easy to put a getter in the `FacebookProvider` class ... but I'm not sure if any developer will ever think of accessing that ... versus referencing documentation, that is.

**Comment by phillip-haydon** [comment]
I would rather not support legacy APIs, so would tag this as a breaking change and forget the old API and start supporting the new API. People will be forced to upgrade eventually when the old API is deprecated. Anyone using the existing API can stay on this version, if they need new features from SA then they upgrade and update their API at the same time.

**Comment by PureKrome** [comment]
So bounce the version from `0.3.whatever-it-is` to `1.0` ?

**Comment by phillip-haydon** [comment]
Yup. That's what we should do. And also start looking at going all OWIN because MS is falling flat on their face with this shit.

**Comment by pmbanugo** [comment]
I think it should support OWIN  and a way of choosing between using OWIN and not.

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by wk001** [comment]
Sorry to go over this again and perhaps I've misunderstood the situation, as I don't know if there are multiple versions of other providers in productions, but I don't think your proposed solution is great (although it fixed my particular problem).  You're basically saying that the latest version of SA will only support the latest version of FB. 

Developers often upgrade without reading the docs - even for a major version change.  If they're using the legacy api they'll only notice the breaking change at runtime - unless you do some nuget-powershell install magic.  That isn't a great experience;  let's hope they have automated tests. 

Now, what of clients who must support the latest version of FB but legacy versions of LinkedIn and Google?  Will SA only support the latest versions of oauth providers?  Apologies for the ridiculous question but you see my point?

SA is essentially a _gateway_ api.  It really needs a pluggable versioning **strategy**.  The default strategy (no-op) would obviously support the latest but devs could opt into specific versions where necessary.

Alternatively, if there were metadata about the provider's app could SA _discover_ what version it should use but a similar api-capability would have to exist with all providers.

**Comment by PureKrome** [comment]
Ok. There's two parts to answer this.

1. SemVer.
2. NuGets per provider.

*SemVer*
So, following proper SemVer, any *breaking* change is with a major version bump. Notice the major word here -> BREAKING. So in this case we tell the developer that the version has a BREAKING CHANGE bump ... so ... read the docs and prepare for stuff to BREAK.

*NuGet's per provider.*
I would like to see each provider have their own nuget. so if one DOES break, it minimizes the upgrade path / effect on others.

Currently, the *current*  code fails now for all people that are using newer facebook-applications. 

This is serious.

As such, it needs to be fixed and i'll use SemVer to help _document_ that something serious has occurred and it's up to the developer to find out what. You don't bump the major number unless there's a really good reason to. The major number is the insurance by all to RTM, IMO.

**Comment by wk001** [comment]
Ah, I didn't realise you'd already planned nuget-per-provider functionality.  My mistake.

This needs to happen quite quickly.

**Comment by PureKrome** [comment]
I didn't plan it for this version. The problem with that is forming a way to 'discover' it. 

I don't -really- have to split the providers into nugets for this patch. the major version bump should be enough to make people be aware that updating will have consequences.

**Comment by phillip-haydon** [comment]
When these OAuth vendors create keys and secrets. They can be used across all versions of their APIs. Example is Google v2 / v3.

We control the version we are using. In most scenarios we give the user more. This seems like a rare scenario where Facebook took something away. 

Us supporting the latest version shouldn't have any real impact unless the user specifies scopes not supported by a new version of the API.

**Comment by PureKrome** [comment]
@phillip-haydon Are you happy with me fixing + pushing up a v1.0 version (as opposed to a different solution).

my fix with be making the next nuget targetting the latest fb api version.

**Comment by phillip-haydon** [comment]
Yeah all good man. Go nuts. We need to talk on hangouts or skype at some
point about SA.

**Comment by PureKrome** [comment]
*Update*: This fix has will have the side-effect of *no username provided* by Facebook. As of API 2.0, FB stopped returning the username of the authenticated user.

**Comment by PureKrome** [comment]
Fixed with c64c124853d4d6e96d5d69ca3bd516fe25938cb5 .

**Comment by PureKrome** [comment]
@wk001 @janoserdelyi 

Heya folks, there's a new `pre-release` build on NuGet with this fix. If you're interesting in testing it out, please give it a run :)

nuget command: `Install-Package SimpleAuthentication.Core -Pre`

(notice that it's a `-pre` package).

**Comment by PureKrome** [comment]
@wk001 and @janoserdelyi - new public release 0.4 is on nuget, if that helps you guys.
