### ISSUE TITLE
Not Getting complete data

### ISSUE THREAD

**Issue by pmbanugo** [SimpleAuthentication/SimpleAuthentication#174]
When using the facebook provider I only get the user's email with the username, and with the twitter provider I get the username without the email from the response.

I'm running the latest version from Nugget. I don't know why I'm having this issues. Any idea what might be the cause?

**Comment by PureKrome** [comment]
Hi @pmbanugo - thanks heaps for the issue.

This was first reported about 48 hours ago: please refer to #173 

I'm working on it, as I type :)

**Comment by phillip-haydon** [comment]
@PureKrome i think he's referring to the fact twitter doesn't give him the email.

@pmbanugo Twitter doesn't give email addresses. It's out of our hands. 

https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558

**Comment by PureKrome** [comment]
Ah my misread. Yep, twitter has never given out email addresses and it's been my PET HATE since day 1!!!!!
