### ISSUE TITLE
How can I 'get current user'?

### ISSUE THREAD

**Issue by troublematic** [SimpleAuthentication/SimpleAuthentication#177]
Hi,

Noob question. I hope this is the right place for it.

I've integrated SimpleAuthentication and it works.
I'd like to be able to 'get the current user' at any time after they log in.
I'm a bit lost as to where to go next.

I've used the ASP.NET Identity system in the past, but on this project I'm using MongoDB, and was hoping to avoid Identity which relies on MS-SQL.

I'm not sure what direction to go in. I think it's either:
 - SimpleAuthentication integrates with ASP Identity, and I should be looking at setting up a MongoDB Identity provider plugin (I think there's a GitHub project which does that).
 - SimpleAuthentication has some 'get user' function I'm not yet aware of, and I roll my own user information storage using an ID from SimpleAuthentication as a unique identifier. And I store away the user profile information when the user first logs in.

Thanks for any help, and thanks for the SA code!
Mark.

**Comment by phillip-haydon** [comment]
Hey,

I think my answer on SO will explain things.

http://stackoverflow.com/questions/18047615/how-do-i-manage-my-authentication-with-worlddomination-and-nancy/18059752#18059752

If it doesn't, let me know.

**Comment by troublematic** [comment]
Thanks Phillip. I've got a bit of learning to do on Forms Auth it seems.
I'll look into it.

Thanks,
Mark.

**Comment by PureKrome** [comment]
The main takeaway point from your question is that you need to manually 'remember' the authenticated user once they have been, well, auth'd.

Personally, I use the `User` property which I think still exists on a normal `HttpContextBase`. I create my own `Identity` class which contains whatever I want to be stored in this `User` property.

With SimpleAuthentication we ask you to create a class that implements `IAuthenticationCallbackProvider`. This is so the code knows what to do, when we have auth'd a user (or failed to auth). So, in this custom code that _you_ have write, this is where you can set up your `CurrentUser` thingy.

sample 1 sec pseduo code...

    public class MyUserIdentity : IIdentity
    {
        public MyUserIdentity(string name)
        {
            Name = name;
        }

        #region IIdentity properties

        public string Name { get; private set; }
        public string AuthenticationType { get { return "My custom cookie auth."; } }
        public bool IsAuthenticated { get { return true; } }

        #endregion

        public string Id { get; set; }
        public string Email { get; set; }
    }

    public class SampleMvcAutoAuthenticationCallbackProvider : IAuthenticationCallbackProvider
    {
        public ActionResult Process(HttpContextBase context, AuthenticateCallbackData model)
        {

            // Don't forget to store this user in your database or whatever, if you need to...

            // Now store this user into the current context of this request.
            var user = new MyUserIdentity(model.AuthenticatedClient.UserInformation.Name)
            {
                Id = model.AuthenticatedClient.UserInformation.Id,
                Email = model.AuthenticatedClient.UserInformation.Email
            };

            context.User = new GenericPrincipal(user, null);

            // Test => Get the current user.
            if (context.User != null &&
                context.User.Identity.IsAuthenticated)
            {
                var name = context.User.Identity.Name;
            }

            // Display a view to the end user, etc.
            return new ViewResult
            {
                ViewName = "AuthenticateCallback",
                ViewData = new ViewDataDictionary(new AuthenticateCallbackViewModel
                {
                    AuthenticatedClient = model.AuthenticatedClient,
                    Exception = model.Exception,
                    ReturnUrl = model.ReturnUrl
                })
            };
        }

**Comment by pmbanugo** [comment]
Thanks @PureKrome I never noticed the context params and have been struggling with some coding issues and you just opened my eyes.

**Comment by troublematic** [comment]
Thanks @PureKrome

**Comment by PureKrome** [comment]
Please gents! I'll close this issue as it seems you're both happy campers :) 

![](http://i.giphy.com/7PzALWNJotBxS.gif)
