### ISSUE TITLE
ProviderName not available on AuthenticateCallbackData

### ISSUE THREAD

**Issue by wk001** [SimpleAuthentication/SimpleAuthentication#178]
At the moment the `ProviderName` is only available on `IAuthenticatedClient`.  It would be convenient if it were available on the `AuthenticateCallbackData` to allow for a strategy-per-provider for error conditions (when the `AuthenticatedClient` isn't populated)

**Comment by PureKrome** [comment]
@wk001 sorry - I don't understand the question :blush:

**Comment by wk001** [comment]
I'd simply like to move the ProviderName property from IAuthenticatedClient up to AuthenticateCallbackData so that, even in the event of an error, I know which provider was used.

This is a tiny change - happy to submit a pr.

**Comment by PureKrome** [comment]
sounds reasonable. PR away!

**Comment by PureKrome** [comment]
@wk001 - Fixed in PR #198

Will be released in v 0.6. Or you can grab the pre-release builds from myget (if you're impatient).

**Comment by PureKrome** [comment]
@wk001 new version 0.6.0 now available on NuGet :+1:
