### ISSUE TITLE
Incompatiblity with RestSharp 105.0.1

### ISSUE THREAD

**Issue by jjchiw** [SimpleAuthentication/SimpleAuthentication#179]
I updated Restsharp and I got this exception while trying to login with twitter `System.MissingMethodException`

Then I searchead for the exception and found this http://stackoverflow.com/questions/27380488/getting-error-method-not-found-void-restsharp-restclient-set-baseurlsystem-s

The nuget package should be changed to now allow greater than 104.x.x or generate a new package built with RestSharp 105.0.1

**Comment by phillip-haydon** [comment]
Unless @PureKrome gets to it before me, I'll try get this updated tonight so he can publish some new packages. 

Or you can send a PR if you like :)

**Comment by jjchiw** [comment]
I sent a PR https://github.com/SimpleAuthentication/SimpleAuthentication/pull/171 fixing this issue with mono https://github.com/SimpleAuthentication/SimpleAuthentication/issues/139#issuecomment-128489625 

I don't know why it's not building in AppVeyor, and since I didn't get any answer I thought that you were not accepting PR.

I can check it tomorrow. :)

**Comment by phillip-haydon** [comment]
Sorry :( I've been out of the game for about 6 months, super busy with projects. I love PRs tho :)

**Comment by PureKrome** [comment]
Fixed with a4ae36e1c99e9d97b89482565297e2608cb53b29.

**Comment by PureKrome** [comment]
@jjchiw Heya mate, there's a new `pre-release` build on NuGet with this fix. If you're interesting in testing it out, please give it a run :)

nuget command: `Install-Package SimpleAuthentication.Core -Pre`

(notice that it's a `-pre` package).

**Comment by jjchiw** [comment]
Yay!

I'll tested during the weekend.

Thanks!
