### ISSUE TITLE
Migrate code to Google+ Signin

### ISSUE THREAD

**Issue by PureKrome** [SimpleAuthentication/SimpleAuthentication#185]
Google is deprecating the `userinfo.profile` and `userinfo.email` scopes, along with the `me` endpoint.

- [x] Replace them with `profile` and `email` scopes
- [x] Refactor the new `me` json payload

**Comment by phillip-haydon** [comment]
https://developers.google.com/+/web/api/rest/oauth#authorization-scopes

Looks like new scopes is defined as:

plus.profile.emails.read

I believe the problem @Cyberlane is having is because of this.

First login authenticates fine, 2nd login causes errors. I'm getting similar issues in the sample app.

**Comment by PureKrome** [comment]
If you check the latest pre-release, etc. this has been applied in this commit: 5de8698714603205ff5e662577d7c40f6cc77920

code ref [is here](https://github.com/SimpleAuthentication/SimpleAuthentication/commit/5de8698714603205ff5e662577d7c40f6cc77920#diff-354c3fe7a51e566642b0e5812f22bdf9R173).

That said, I'm using the following scopes: `profile email` .. not `plus.profile.emails.read`.

**Comment by PureKrome** [comment]
(please review the latest nuget package so we can put this all to bed). *hint* :wink:

**Comment by Cyberlane** [comment]
I would happily test it, but I do not see a NuGet package... :grin:

**Comment by PureKrome** [comment]
https://www.nuget.org/packages/SimpleAuthentication.Core/0.3.23-dev

**Comment by Cyberlane** [comment]
:boom: it works perfectly every time now!

:shipit:

**Comment by phillip-haydon** [comment]
IM SORRY @PureKrome god damnit, I looked at the PR that was merged and tested the latest version not the pre-release version.

Ok if @Cyberlane is happy with it working then lets push it to prod.

**Comment by PureKrome** [comment]
Fixed in PR #189

**Comment by PureKrome** [comment]
@Cyberlane New 0.4 nuget package uploaded to NuGet for you :+1:
