### ISSUE TITLE
AuthenticatedClient when using Google is null

### ISSUE THREAD

**Issue by Cyberlane** [SimpleAuthentication/SimpleAuthentication#187]
4 days ago I got this up and running in a very rough manner, I could click the login button and it would hit the `AuthenticationCallbackProvider` with all the correct user data. I then needed to actually create a logged in session with that, so I decided to use `Nancy Forms Authentication`, and followed two blog posts on this subject created by Phillip.
After I wired it all up, I decided to test my code to see how it looked and found my `AuthenticatedClient` property was null, even though I clicked the `Accept` button on my Google login screen. The key and secret are exactly the same as before, I have confirmed the login URL and the authentication URL is still the same, but it is just not working. I am wondering if perhaps Google is caching something from my previous successful login and simply not providing the client data second time, or what could possibly be wrong?

For clarification, I am using the `Other` option, instead of `Web` with the key I made with Google, simply because this one does not require any URLs, and as I said earlier... it worked just fine before.

I am clutching at straws here and have no idea what could be wrong. I am more than happy to share any information or code required to help me diagnose this issue, just ask!

**Comment by PureKrome** [comment]
@Cyberlane Does this problem still exist, with the latest release?

**Comment by Cyberlane** [comment]
@PureKrome negative, it is resolved. As @phillip-haydon mentioned in the other issue, it is a result of signing in once and it works, and each attempt after fails... all due to the new Google API!
