### ISSUE TITLE
Dead project takeover

### ISSUE THREAD

**Issue by pashute** [SimpleAuthentication/SimpleAuthentication#188]
In the jabbr page https://jabbr.net/#/rooms/SimpleAuthentication @jonh04 offered to take over, if the project is actually dead as it seems. Is it? Are you interested?

**Comment by PureKrome** [comment]
I'm still here. project isn't really dead. The other guy Phillip is prolly half dead cause he takes ages to get around to doing any SA stuff.

We're interesting in people helping of course! so sure .. if someone wants to help in the jabbr room - awesome!

**Comment by phillip-haydon** [comment]
Happy to have people help for sure. 

I'm just super busy working on a personal project which I'm hoping to launch soon. And I'm sorta specing out an OWIN branch of SA.

**Comment by PureKrome** [comment]
Closing issue -> we're very happy to have people help us. Project isn't dead, just has low traffic.
