### ISSUE TITLE
Twitter provider RetrieveAccessToken validation VerifierResult error

### ISSUE THREAD

**Issue by kukidon** [SimpleAuthentication/SimpleAuthentication#192]
When you try to retrieve access token from twitter you check for `null` field of `VerifierResult` (`TwitterProvider.cs`, `private AccessTokenResult RetrieveAccessToken(VerifierResult verifierResult) method`). You check twice `verifierResult.OAuthToken` for null instead of checking `verifierResult.OAuthToken` and `verifierResult.OAuthVerifier` both.

**Comment by PureKrome** [comment]
@kukidon new version 0.6.0 now available on NuGet :+1:
