### ISSUE TITLE
GenderType should return Unknown when input is null

### ISSUE THREAD

**Issue by mattiasd** [SimpleAuthentication/SimpleAuthentication#193]
In some cases facebook doesn't return gender and then gender parsing throws and the login fails.

**Comment by PureKrome** [comment]
As mentioned in the PR you submitted, I'm pretty strict on making sure methods check for Null/Empty if they should not be passed in (and throwing when found).

So FB needs to check this BEFORE calling the method. Ironically, the Google Provider [is already doing this check](https://github.com/SimpleAuthentication/SimpleAuthentication/blob/master/Code/SimpleAuthentication.Core/Providers/GoogleProvider.cs#L149) so I've just copied that code, to the Facebook Provider.

**Comment by mattiasd** [comment]
Fine with me. Tanks for the great work!

**Comment by PureKrome** [comment]
[Here's the fix](https://github.com/SimpleAuthentication/SimpleAuthentication/blob/dev/Code/SimpleAuthentication.Core/Providers/FacebookProvider.cs#L225), btw :smile:

**Comment by PureKrome** [comment]
Fixed in #196

**Comment by PureKrome** [comment]
@mattiasd new version 0.6.0 now available on NuGet :+1:
