### ISSUE TITLE
Is there a plan to implement provider for Yahoo

### ISSUE THREAD

**Issue by zahidmadeel** [SimpleAuthentication/SimpleAuthentication#212]
Hi, 

I have been using your API to integrate with google, facebook, twitter and windows live. I also need to integrate with yahoo but I found no provider for yahoo neither in core project nor in extra providers project. Is there a plan to roll out a provider for yahoo?

Regards
Adeel

**Comment by PureKrome** [comment]
No plan from me and i'm assuming no plan from Phillip.

We will accept a PR for it, though.

GL :+1:

**Comment by phillip-haydon** [comment]
I didn't know Yahoo was still used by people, thought people used gmail to login to yahoo.

**Comment by zahidmadeel** [comment]
NP, I will try to implement it and If I succeeded, I will create a pull
request on your repo. I think, I should put it in ExtraProviders project,
right?

On 22 June 2016 at 17:51, Phillip Haydon <notifications@github.com> wrote:

> I didn't know Yahoo was still used by people, thought people used gmail to
> login to yahoo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimpleAuthentication/SimpleAuthentication/issues/212#issuecomment-227732961>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABBKjLtaLTKSe5_K-ur4CD9fSnKDPT6xks5qOS_DgaJpZM4I7mVT>
> .
>



-- 
Regards
Muhammad Adeel Zahid

**Comment by PureKrome** [comment]
Yep - that's correct. GL :+1:

**Comment by zahidmadeel** [comment]
Hi SimpleAuthentication/SimpleAuthentication

You have been invited to join the Cook at Home https://u3431732.ct.sendgrid.net/wf/click?upn=QgBgXNb9qe6bSBTooCR18ecl8fVTnBcGrCB-2BcpvqGpx9BZijN5ezGCHSiX1BlHqX_s5UH8bhnBaopYjthcNSRccgGEPCgo2wwm-2FsOE4oLDazYxlfmDhl1YobY9pwG6aclcFKUobUJJCG7pz-2Ft-2BNbYNqZI56NgE660HxAarqFgpK4ug8r97tNfmtCT0w19XVKgHMmgH13G5qna9aoxuE-2BlbnGHfkJbWPBzqNSIGhp16JQBi4fYcE1xBySPZrTqj-2F-2F6PfaOZBtWbVDPQpC96VBWRkaq4nH4k-2F8OrHtsalX0fENLeCtu6d9TYC-2Bcw8xbbjyYWRfcP9T-2B4za9olQQp-2BBCH17tg4T3NNxUlMSFRCmW0wf-2BBHAWKDfL-2BnYevhdZxRON1CnI4T4AtNU4q4V-2Ba43N3iWDenfylxRnoWR4Lvz8zC4XYDhhxS3-2Bfxe9GfEF-2BD9H0CsuOH1KnMNcsALcl8SnMg-3D-3D

 

Regards

Cook at Home Team

**Comment by zahidmadeel** [comment]
Hi SimpleAuthentication/SimpleAuthentication

 

You have been invited to join the Cook at Home.

 

 


Regards

Cook at Home Team
