### ISSUE TITLE
The Google provider won't work after Januar 28, 2019 (I think)

### ISSUE THREAD

**Issue by ThomasArdal** [SimpleAuthentication/SimpleAuthentication#223]
I know this project is deprecated and this is mostly for info. Google is shutting down Google+ and the Google+ API. `GoogleProvider` is using Google+ APIs (like `/plus/v1/people/me`) in the `RetrieveUserInformation`-method. I don't think that this will work after January 28, 2019. Google writes the following:

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

When looking at the code, I think that the google provider will break on this day.

**Comment by PureKrome** [comment]
That would be lovely @ThomasArdal - i'm not sure what other alternatives there are though. I should also have some bandwidth this 🎄 -> 🎆 to update this, too. _maybe_ even move it to .NET Standard. (maybe ... bandwidth permitting).

**Comment by ThomasArdal** [comment]
You're right. Moving to .NET Standard wouldn't make sense unless you want to revive the package or something like that. Would be great if the google provider worked for projects already using it.

I'll take a look when I have time :smile:

**Comment by ThomasArdal** [comment]
There you go: https://github.com/SimpleAuthentication/SimpleAuthentication/pull/224
