### ISSUE TITLE
IE 8 Mime Type issue

### ISSUE THREAD

**Issue by jchannon** [SimpleAuthentication/SimpleAuthentication#55]
If I execute this URL in IE I get the below. I asssume its a Mime issue.

http://localhost:12008/authentication/authenticatecallback?code=5195dcfd79c9327f2535&providerkey=github&state=190d1b5d-3981-4fb8-892e-20fa838e2e89

![capture_e02a](https://f.cloud.github.com/assets/105126/482195/69e6865a-b88c-11e2-85f1-55283d54f473.png)

**Comment by phillip-haydon** [comment]
This issue is dead. Happened only in Fiddler if I recall and fixed in Nancy? Either way IE8 is pretty much dead.
