### ISSUE TITLE
Support for Claims

### ISSUE THREAD

**Issue by PureKrome** [SimpleAuthentication/SimpleAuthentication#85]
Add support for Claims.

Checklist
- [ ] Create an enumeration that lists the common claims
- [ ] Update the `app.config` to accept this list of enumerations
- [ ] Handle the code that maps the enumeration to the real scopes.
- [ ] Tests for the scopes
- [ ] Documentation on Default Scopes and Custom Scopes

**Comment by dbones** [comment]
+1

**Comment by PureKrome** [comment]
Issue is closed because we'll open up the claims string in the vnext release. A new card will be created, for this.
